import type { Station } from "./types";

export const stations: Station[] = [
    // ═══════════════════════════════════════════
    // ALPES DU NORD
    // ═══════════════════════════════════════════
    {
        id: "val-thorens",
        name: "Val Thorens",
        slug: "val-thorens",
        massif: "Vanoise",
        region: "Alpes du Nord",
        lat: 45.2981,
        lon: 6.5800,
        altitudeVillage: 2300,
        altitudeMin: 2300,
        altitudeMax: 3230,
        kmPistes: 150,
        openMeteoElevation: 2800,
        snowForecastSlug: "Val-Thorens",
        skiinfoSlug: "val-thorens",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "tignes",
        name: "Tignes",
        slug: "tignes",
        massif: "Haute-Tarentaise",
        region: "Alpes du Nord",
        lat: 45.4683,
        lon: 6.9056,
        altitudeVillage: 2100,
        altitudeMin: 1550,
        altitudeMax: 3456,
        kmPistes: 300,
        openMeteoElevation: 2700,
        snowForecastSlug: "Tignes",
        skiinfoSlug: "tignes",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "val-disere",
        name: "Val d'Isère",
        slug: "val-disere",
        massif: "Haute-Tarentaise",
        region: "Alpes du Nord",
        lat: 45.4486,
        lon: 6.9806,
        altitudeVillage: 1850,
        altitudeMin: 1550,
        altitudeMax: 3456,
        kmPistes: 300,
        openMeteoElevation: 2600,
        snowForecastSlug: "Val-d-Isere",
        skiinfoSlug: "val-d-isere",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "les-arcs",
        name: "Les Arcs",
        slug: "les-arcs",
        massif: "Haute-Tarentaise",
        region: "Alpes du Nord",
        lat: 45.5733,
        lon: 6.8281,
        altitudeVillage: 1800,
        altitudeMin: 1200,
        altitudeMax: 3226,
        kmPistes: 200,
        openMeteoElevation: 2300,
        snowForecastSlug: "Les-Arcs",
        skiinfoSlug: "les-arcs",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "la-plagne",
        name: "La Plagne",
        slug: "la-plagne",
        massif: "Vanoise",
        region: "Alpes du Nord",
        lat: 45.5069,
        lon: 6.6775,
        altitudeVillage: 2050,
        altitudeMin: 1250,
        altitudeMax: 3250,
        kmPistes: 225,
        openMeteoElevation: 2400,
        snowForecastSlug: "La-Plagne",
        skiinfoSlug: "la-plagne",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "les-menuires",
        name: "Les Menuires",
        slug: "les-menuires",
        massif: "Vanoise",
        region: "Alpes du Nord",
        lat: 45.3264,
        lon: 6.5328,
        altitudeVillage: 1815,
        altitudeMin: 1400,
        altitudeMax: 3230,
        kmPistes: 160,
        openMeteoElevation: 2400,
        snowForecastSlug: "Les-Menuires",
        skiinfoSlug: "les-menuires",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "meribel",
        name: "Méribel",
        slug: "meribel",
        massif: "Vanoise",
        region: "Alpes du Nord",
        lat: 45.3968,
        lon: 6.5656,
        altitudeVillage: 1450,
        altitudeMin: 1100,
        altitudeMax: 3230,
        kmPistes: 150,
        openMeteoElevation: 2200,
        snowForecastSlug: "Meribel",
        skiinfoSlug: "meribel",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "courchevel",
        name: "Courchevel",
        slug: "courchevel",
        massif: "Vanoise",
        region: "Alpes du Nord",
        lat: 45.4153,
        lon: 6.6347,
        altitudeVillage: 1850,
        altitudeMin: 1300,
        altitudeMax: 3230,
        kmPistes: 150,
        openMeteoElevation: 2300,
        snowForecastSlug: "Courchevel",
        skiinfoSlug: "courchevel",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "la-rosiere",
        name: "La Rosière",
        slug: "la-rosiere",
        massif: "Haute-Tarentaise",
        region: "Alpes du Nord",
        lat: 45.6278,
        lon: 6.8489,
        altitudeVillage: 1850,
        altitudeMin: 1176,
        altitudeMax: 2800,
        kmPistes: 160,
        openMeteoElevation: 2200,
        snowForecastSlug: "La-Rosiere",
        skiinfoSlug: "la-rosiere-espace-san-bernardo",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "avoriaz",
        name: "Avoriaz",
        slug: "avoriaz",
        massif: "Chablais",
        region: "Alpes du Nord",
        lat: 46.1911,
        lon: 6.7744,
        altitudeVillage: 1800,
        altitudeMin: 1100,
        altitudeMax: 2466,
        kmPistes: 310,
        openMeteoElevation: 2100,
        snowForecastSlug: "Avoriaz",
        skiinfoSlug: "avoriaz",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "les-gets",
        name: "Les Gets",
        slug: "les-gets",
        massif: "Chablais",
        region: "Alpes du Nord",
        lat: 46.1592,
        lon: 6.6694,
        altitudeVillage: 1172,
        altitudeMin: 1000,
        altitudeMax: 2002,
        kmPistes: 120,
        openMeteoElevation: 1600,
        snowForecastSlug: "Les-Gets",
        skiinfoSlug: "les-gets",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "morzine",
        name: "Morzine",
        slug: "morzine",
        massif: "Chablais",
        region: "Alpes du Nord",
        lat: 46.1797,
        lon: 6.7094,
        altitudeVillage: 1000,
        altitudeMin: 1000,
        altitudeMax: 2466,
        kmPistes: 310,
        openMeteoElevation: 1800,
        snowForecastSlug: "Morzine",
        skiinfoSlug: "morzine",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "chamonix",
        name: "Chamonix",
        slug: "chamonix",
        massif: "Mont-Blanc",
        region: "Alpes du Nord",
        lat: 45.9237,
        lon: 6.8694,
        altitudeVillage: 1035,
        altitudeMin: 1035,
        altitudeMax: 3842,
        kmPistes: 155,
        openMeteoElevation: 2500,
        snowForecastSlug: "Chamonix",
        skiinfoSlug: "chamonix-mont-blanc",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "megeve",
        name: "Megève",
        slug: "megeve",
        massif: "Mont-Blanc",
        region: "Alpes du Nord",
        lat: 45.8567,
        lon: 6.6175,
        altitudeVillage: 1113,
        altitudeMin: 850,
        altitudeMax: 2350,
        kmPistes: 235,
        openMeteoElevation: 1800,
        snowForecastSlug: "Megeve",
        skiinfoSlug: "megeve",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "la-clusaz",
        name: "La Clusaz",
        slug: "la-clusaz",
        massif: "Aravis",
        region: "Alpes du Nord",
        lat: 45.9044,
        lon: 6.4244,
        altitudeVillage: 1100,
        altitudeMin: 1100,
        altitudeMax: 2600,
        kmPistes: 125,
        openMeteoElevation: 1900,
        snowForecastSlug: "La-Clusaz",
        skiinfoSlug: "la-clusaz",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "le-grand-bornand",
        name: "Le Grand-Bornand",
        slug: "le-grand-bornand",
        massif: "Aravis",
        region: "Alpes du Nord",
        lat: 45.9419,
        lon: 6.4297,
        altitudeVillage: 1000,
        altitudeMin: 1000,
        altitudeMax: 2100,
        kmPistes: 90,
        openMeteoElevation: 1600,
        snowForecastSlug: "Le-Grand-Bornand",
        skiinfoSlug: "le-grand-bornand",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "flaine",
        name: "Flaine",
        slug: "flaine",
        massif: "Faucigny",
        region: "Alpes du Nord",
        lat: 46.0061,
        lon: 6.6897,
        altitudeVillage: 1600,
        altitudeMin: 700,
        altitudeMax: 2500,
        kmPistes: 265,
        openMeteoElevation: 2100,
        snowForecastSlug: "Flaine",
        skiinfoSlug: "flaine",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "les-contamines",
        name: "Les Contamines",
        slug: "les-contamines",
        massif: "Mont-Blanc",
        region: "Alpes du Nord",
        lat: 45.8211,
        lon: 6.7267,
        altitudeVillage: 1164,
        altitudeMin: 1164,
        altitudeMax: 2500,
        kmPistes: 120,
        openMeteoElevation: 1900,
        snowForecastSlug: "Les-Contamines",
        skiinfoSlug: "les-contamines-montjoie",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "sainte-foy",
        name: "Sainte-Foy Tarentaise",
        slug: "sainte-foy",
        massif: "Haute-Tarentaise",
        region: "Alpes du Nord",
        lat: 45.5833,
        lon: 6.8833,
        altitudeVillage: 1550,
        altitudeMin: 1550,
        altitudeMax: 2620,
        kmPistes: 42,
        openMeteoElevation: 2100,
        snowForecastSlug: "Sainte-Foy-Tarentaise",
        skiinfoSlug: "sainte-foy-tarentaise",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "valfrejus",
        name: "Valfréjus",
        slug: "valfrejus",
        massif: "Maurienne",
        region: "Alpes du Nord",
        lat: 45.1833,
        lon: 6.6500,
        altitudeVillage: 1550,
        altitudeMin: 1550,
        altitudeMax: 2737,
        kmPistes: 65,
        openMeteoElevation: 2200,
        snowForecastSlug: "Valfrejus",
        skiinfoSlug: "valfrejus",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "valmeinier",
        name: "Valmeinier",
        slug: "valmeinier",
        massif: "Maurienne",
        region: "Alpes du Nord",
        lat: 45.1833,
        lon: 6.4833,
        altitudeVillage: 1500,
        altitudeMin: 1500,
        altitudeMax: 2600,
        kmPistes: 165,
        openMeteoElevation: 2100,
        snowForecastSlug: "Valmeinier",
        skiinfoSlug: "valmeinier",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "valloire",
        name: "Valloire",
        slug: "valloire",
        massif: "Maurienne",
        region: "Alpes du Nord",
        lat: 45.1667,
        lon: 6.4333,
        altitudeVillage: 1430,
        altitudeMin: 1430,
        altitudeMax: 2600,
        kmPistes: 165,
        openMeteoElevation: 2100,
        snowForecastSlug: "Valloire",
        skiinfoSlug: "valloire",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "les-sybelles",
        name: "Les Sybelles",
        slug: "les-sybelles",
        massif: "Maurienne",
        region: "Alpes du Nord",
        lat: 45.2333,
        lon: 6.2333,
        altitudeVillage: 1600,
        altitudeMin: 1100,
        altitudeMax: 2620,
        kmPistes: 310,
        openMeteoElevation: 2100,
        snowForecastSlug: "Les-Sybelles",
        skiinfoSlug: "les-sybelles-le-corbier",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "les-karellis",
        name: "Les Karellis",
        slug: "les-karellis",
        massif: "Maurienne",
        region: "Alpes du Nord",
        lat: 45.2167,
        lon: 6.4000,
        altitudeVillage: 1600,
        altitudeMin: 1600,
        altitudeMax: 2520,
        kmPistes: 60,
        openMeteoElevation: 2100,
        snowForecastSlug: "Les-Karellis",
        skiinfoSlug: "les-karellis",
        skiinfoRegion: "alpes-du-nord",
    },
    {
        id: "aussois",
        name: "Aussois",
        slug: "aussois",
        massif: "Maurienne",
        region: "Alpes du Nord",
        lat: 45.2281,
        lon: 6.7442,
        altitudeVillage: 1500,
        altitudeMin: 1500,
        altitudeMax: 2750,
        kmPistes: 55,
        openMeteoElevation: 2100,
        snowForecastSlug: "Aussois",
        skiinfoSlug: "aussois",
        skiinfoRegion: "alpes-du-nord",
    },

    // ═══════════════════════════════════════════
    // ALPES DU SUD
    // ═══════════════════════════════════════════
    {
        id: "serre-chevalier",
        name: "Serre Chevalier",
        slug: "serre-chevalier",
        massif: "Écrins",
        region: "Alpes du Sud",
        lat: 44.9478,
        lon: 6.5872,
        altitudeVillage: 1200,
        altitudeMin: 1200,
        altitudeMax: 2800,
        kmPistes: 250,
        openMeteoElevation: 2200,
        snowForecastSlug: "Serre-Chevalier",
        skiinfoSlug: "serre-chevalier",
        skiinfoRegion: "alpes-du-sud",
    },
    {
        id: "alpe-dhuez",
        name: "Alpe d'Huez",
        slug: "alpe-dhuez",
        massif: "Grandes Rousses",
        region: "Alpes du Sud",
        lat: 45.0919,
        lon: 6.0686,
        altitudeVillage: 1860,
        altitudeMin: 1120,
        altitudeMax: 3330,
        kmPistes: 250,
        openMeteoElevation: 2600,
        snowForecastSlug: "Alpe-d-Huez",
        skiinfoSlug: "alpe-d-huez",
        skiinfoRegion: "alpes-du-sud",
    },
    {
        id: "les-deux-alpes",
        name: "Les 2 Alpes",
        slug: "les-deux-alpes",
        massif: "Écrins",
        region: "Alpes du Sud",
        lat: 45.0167,
        lon: 6.1222,
        altitudeVillage: 1650,
        altitudeMin: 1300,
        altitudeMax: 3600,
        kmPistes: 225,
        openMeteoElevation: 2700,
        snowForecastSlug: "Les-Deux-Alpes",
        skiinfoSlug: "les-2-alpes",
        skiinfoRegion: "alpes-du-sud",
    },
    {
        id: "montgenèvre",
        name: "Montgenèvre",
        slug: "montgenevre",
        massif: "Briançonnais",
        region: "Alpes du Sud",
        lat: 44.9325,
        lon: 6.7239,
        altitudeVillage: 1860,
        altitudeMin: 1860,
        altitudeMax: 2700,
        kmPistes: 100,
        openMeteoElevation: 2300,
        snowForecastSlug: "Montgenevre",
        skiinfoSlug: "montgenevre",
        skiinfoRegion: "alpes-du-sud",
    },
    {
        id: "vars",
        name: "Vars",
        slug: "vars",
        massif: "Queyras",
        region: "Alpes du Sud",
        lat: 44.5589,
        lon: 6.6908,
        altitudeVillage: 1850,
        altitudeMin: 1650,
        altitudeMax: 2750,
        kmPistes: 185,
        openMeteoElevation: 2300,
        snowForecastSlug: "Vars",
        skiinfoSlug: "vars",
        skiinfoRegion: "alpes-du-sud",
    },
    {
        id: "risoul",
        name: "Risoul",
        slug: "risoul",
        massif: "Queyras",
        region: "Alpes du Sud",
        lat: 44.6253,
        lon: 6.6378,
        altitudeVillage: 1850,
        altitudeMin: 1850,
        altitudeMax: 2750,
        kmPistes: 185,
        openMeteoElevation: 2300,
        snowForecastSlug: "Risoul",
        skiinfoSlug: "risoul-la-foret-blanche",
        skiinfoRegion: "alpes-du-sud",
    },
    {
        id: "pra-loup",
        name: "Pra Loup",
        slug: "pra-loup",
        massif: "Ubaye",
        region: "Alpes du Sud",
        lat: 44.3667,
        lon: 6.6000,
        altitudeVillage: 1600,
        altitudeMin: 1500,
        altitudeMax: 2600,
        kmPistes: 180,
        openMeteoElevation: 2100,
        snowForecastSlug: "Pra-Loup",
        skiinfoSlug: "pra-loup",
        skiinfoRegion: "alpes-du-sud",
    },
    {
        id: "isola-2000",
        name: "Isola 2000",
        slug: "isola-2000",
        massif: "Mercantour",
        region: "Alpes du Sud",
        lat: 44.1867,
        lon: 7.1614,
        altitudeVillage: 2000,
        altitudeMin: 1800,
        altitudeMax: 2610,
        kmPistes: 120,
        openMeteoElevation: 2300,
        snowForecastSlug: "Isola-2000",
        skiinfoSlug: "isola-2000",
        skiinfoRegion: "alpes-du-sud",
    },
    {
        id: "auron",
        name: "Auron",
        slug: "auron",
        massif: "Mercantour",
        region: "Alpes du Sud",
        lat: 44.2081,
        lon: 6.9331,
        altitudeVillage: 1600,
        altitudeMin: 1600,
        altitudeMax: 2450,
        kmPistes: 135,
        openMeteoElevation: 2000,
        snowForecastSlug: "Auron",
        skiinfoSlug: "auron",
        skiinfoRegion: "alpes-du-sud",
    },
    {
        id: "la-foux-dallos",
        name: "La Foux d'Allos",
        slug: "la-foux-dallos",
        massif: "Ubaye",
        region: "Alpes du Sud",
        lat: 44.3000,
        lon: 6.5667,
        altitudeVillage: 1800,
        altitudeMin: 1800,
        altitudeMax: 2600,
        kmPistes: 180,
        openMeteoElevation: 2200,
        snowForecastSlug: "La-Foux-d-Allos",
        skiinfoSlug: "val-d-allos-la-foux",
        skiinfoRegion: "alpes-du-sud",
    },
    {
        id: "orcières",
        name: "Orcières Merlette",
        slug: "orcieres",
        massif: "Champsaur",
        region: "Alpes du Sud",
        lat: 44.6939,
        lon: 6.3247,
        altitudeVillage: 1850,
        altitudeMin: 1850,
        altitudeMax: 2725,
        kmPistes: 100,
        openMeteoElevation: 2300,
        snowForecastSlug: "Orcieres-Merlette",
        skiinfoSlug: "orcieres-merlette-1850",
        skiinfoRegion: "alpes-du-sud",
    },
    {
        id: "superdevoluy",
        name: "SuperDévoluy",
        slug: "superdevoluy",
        massif: "Dévoluy",
        region: "Alpes du Sud",
        lat: 44.6833,
        lon: 5.9167,
        altitudeVillage: 1500,
        altitudeMin: 1500,
        altitudeMax: 2500,
        kmPistes: 100,
        openMeteoElevation: 2000,
        snowForecastSlug: "SuperDevoluy",
        skiinfoSlug: "superdevoluy",
        skiinfoRegion: "alpes-du-sud",
    },

    // ═══════════════════════════════════════════
    // PYRÉNÉES
    // ═══════════════════════════════════════════
    {
        id: "grand-tourmalet",
        name: "Grand Tourmalet",
        slug: "grand-tourmalet",
        massif: "Pyrénées centrales",
        region: "Pyrénées",
        lat: 42.9089,
        lon: 0.1500,
        altitudeVillage: 1400,
        altitudeMin: 1400,
        altitudeMax: 2500,
        kmPistes: 100,
        openMeteoElevation: 2000,
        snowForecastSlug: "Bareges-La-Mongie",
        skiinfoSlug: "bareges-la-mongie-grand-tourmalet",
        skiinfoRegion: "pyrenees",
    },
    {
        id: "cauterets",
        name: "Cauterets",
        slug: "cauterets",
        massif: "Pyrénées centrales",
        region: "Pyrénées",
        lat: 42.8892,
        lon: -0.1117,
        altitudeVillage: 930,
        altitudeMin: 1730,
        altitudeMax: 2450,
        kmPistes: 36,
        openMeteoElevation: 2100,
        snowForecastSlug: "Cauterets",
        skiinfoSlug: "cauterets",
        skiinfoRegion: "pyrenees",
    },
    {
        id: "saint-lary",
        name: "Saint-Lary Soulan",
        slug: "saint-lary",
        massif: "Pyrénées centrales",
        region: "Pyrénées",
        lat: 42.8167,
        lon: 0.3167,
        altitudeVillage: 830,
        altitudeMin: 1680,
        altitudeMax: 2515,
        kmPistes: 100,
        openMeteoElevation: 2100,
        snowForecastSlug: "Saint-Lary",
        skiinfoSlug: "saint-lary-soulan",
        skiinfoRegion: "pyrenees",
    },
    {
        id: "peyragudes",
        name: "Peyragudes",
        slug: "peyragudes",
        massif: "Pyrénées centrales",
        region: "Pyrénées",
        lat: 42.7833,
        lon: 0.4500,
        altitudeVillage: 1600,
        altitudeMin: 1600,
        altitudeMax: 2400,
        kmPistes: 60,
        openMeteoElevation: 2000,
        snowForecastSlug: "Peyragudes",
        skiinfoSlug: "peyragudes",
        skiinfoRegion: "pyrenees",
    },
    {
        id: "font-romeu",
        name: "Font-Romeu Pyrénées 2000",
        slug: "font-romeu",
        massif: "Pyrénées orientales",
        region: "Pyrénées",
        lat: 42.5028,
        lon: 2.0372,
        altitudeVillage: 1800,
        altitudeMin: 1700,
        altitudeMax: 2213,
        kmPistes: 43,
        openMeteoElevation: 2000,
        snowForecastSlug: "Font-Romeu",
        skiinfoSlug: "font-romeu-pyrenees-2000",
        skiinfoRegion: "pyrenees",
    },
    {
        id: "les-angles",
        name: "Les Angles",
        slug: "les-angles",
        massif: "Pyrénées orientales",
        region: "Pyrénées",
        lat: 42.5667,
        lon: 2.0667,
        altitudeVillage: 1650,
        altitudeMin: 1650,
        altitudeMax: 2400,
        kmPistes: 55,
        openMeteoElevation: 2000,
        snowForecastSlug: "Les-Angles",
        skiinfoSlug: "les-angles",
        skiinfoRegion: "pyrenees",
    },
    {
        id: "ax-3-domaines",
        name: "Ax 3 Domaines",
        slug: "ax-3-domaines",
        massif: "Pyrénées ariégeoises",
        region: "Pyrénées",
        lat: 42.7203,
        lon: 1.8375,
        altitudeVillage: 1400,
        altitudeMin: 1400,
        altitudeMax: 2400,
        kmPistes: 75,
        openMeteoElevation: 1900,
        snowForecastSlug: "Ax-3-Domaines",
        skiinfoSlug: "ax-3-domaines",
        skiinfoRegion: "pyrenees",
    },
    {
        id: "gourette",
        name: "Gourette",
        slug: "gourette",
        massif: "Pyrénées atlantiques",
        region: "Pyrénées",
        lat: 42.9606,
        lon: -0.3361,
        altitudeVillage: 1400,
        altitudeMin: 1400,
        altitudeMax: 2450,
        kmPistes: 35,
        openMeteoElevation: 1900,
        snowForecastSlug: "Gourette",
        skiinfoSlug: "gourette",
        skiinfoRegion: "pyrenees",
    },
    {
        id: "la-pierre-saint-martin",
        name: "La Pierre Saint-Martin",
        slug: "la-pierre-saint-martin",
        massif: "Pyrénées atlantiques",
        region: "Pyrénées",
        lat: 42.9667,
        lon: -0.7500,
        altitudeVillage: 1527,
        altitudeMin: 1527,
        altitudeMax: 2153,
        kmPistes: 30,
        openMeteoElevation: 1800,
        snowForecastSlug: "La-Pierre-Saint-Martin",
        skiinfoSlug: "la-pierre-saint-martin",
        skiinfoRegion: "pyrenees",
    },
    {
        id: "luz-ardiden",
        name: "Luz Ardiden",
        slug: "luz-ardiden",
        massif: "Pyrénées centrales",
        region: "Pyrénées",
        lat: 42.8833,
        lon: -0.0667,
        altitudeVillage: 1680,
        altitudeMin: 1680,
        altitudeMax: 2500,
        kmPistes: 60,
        openMeteoElevation: 2100,
        snowForecastSlug: "Luz-Ardiden",
        skiinfoSlug: "luz-ardiden",
        skiinfoRegion: "pyrenees",
    },

    // ═══════════════════════════════════════════
    // MASSIF CENTRAL + JURA + VOSGES
    // ═══════════════════════════════════════════
    {
        id: "super-besse",
        name: "Super Besse",
        slug: "super-besse",
        massif: "Massif Central",
        region: "Massif Central",
        lat: 45.5075,
        lon: 2.8517,
        altitudeVillage: 1350,
        altitudeMin: 1350,
        altitudeMax: 1850,
        kmPistes: 43,
        openMeteoElevation: 1600,
        snowForecastSlug: "Super-Besse",
        skiinfoSlug: "super-besse",
        skiinfoRegion: "massif-central",
    },
    {
        id: "le-mont-dore",
        name: "Le Mont-Dore",
        slug: "le-mont-dore",
        massif: "Massif Central",
        region: "Massif Central",
        lat: 45.5736,
        lon: 2.8094,
        altitudeVillage: 1050,
        altitudeMin: 1200,
        altitudeMax: 1846,
        kmPistes: 33,
        openMeteoElevation: 1500,
        snowForecastSlug: "Le-Mont-Dore",
        skiinfoSlug: "le-mont-dore",
        skiinfoRegion: "massif-central",
    },
    {
        id: "le-lioran",
        name: "Le Lioran",
        slug: "le-lioran",
        massif: "Massif Central",
        region: "Massif Central",
        lat: 45.0833,
        lon: 2.7500,
        altitudeVillage: 1160,
        altitudeMin: 1160,
        altitudeMax: 1850,
        kmPistes: 60,
        openMeteoElevation: 1500,
        snowForecastSlug: "Le-Lioran",
        skiinfoSlug: "le-lioran",
        skiinfoRegion: "massif-central",
    },
    {
        id: "metabief",
        name: "Métabief",
        slug: "metabief",
        massif: "Jura",
        region: "Jura",
        lat: 46.7706,
        lon: 6.3536,
        altitudeVillage: 1000,
        altitudeMin: 900,
        altitudeMax: 1463,
        kmPistes: 40,
        openMeteoElevation: 1200,
        snowForecastSlug: "Metabief",
        skiinfoSlug: "metabief",
        skiinfoRegion: "jura",
    },
    {
        id: "la-bresse",
        name: "La Bresse Hohneck",
        slug: "la-bresse",
        massif: "Vosges",
        region: "Vosges",
        lat: 48.0000,
        lon: 6.9500,
        altitudeVillage: 900,
        altitudeMin: 900,
        altitudeMax: 1350,
        kmPistes: 50,
        openMeteoElevation: 1100,
        snowForecastSlug: "La-Bresse-Hohneck",
        skiinfoSlug: "la-bresse-hohneck",
        skiinfoRegion: "vosges",
    },
];
