import type { Station } from "./types";

export const stations: Station[] = [
    // ──────── MONT-BLANC ────────
    {
        id: "chamonix",
        name: "Chamonix Mont-Blanc",
        slug: "chamonix",
        massif: "Mont-Blanc",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.9237,
        lon: 6.8694,
        altitudeVillage: 1035,
        altitudeMin: 1035,
        altitudeMax: 3842,
        kmPistes: 155,
        openMeteoElevation: 3000,
        snowForecastSlug: "Chamonix",
        skiinfoSlug: "chamonix",
    },
    {
        id: "megeve",
        name: "Megève",
        slug: "megeve",
        massif: "Mont-Blanc",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.8567,
        lon: 6.6175,
        altitudeVillage: 1113,
        altitudeMin: 850,
        altitudeMax: 2350,
        kmPistes: 400,
        openMeteoElevation: 2000,
        snowForecastSlug: "Megeve",
        skiinfoSlug: "megeve",
    },
    {
        id: "les-contamines",
        name: "Les Contamines-Montjoie",
        slug: "les-contamines",
        massif: "Mont-Blanc",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.8211,
        lon: 6.7267,
        altitudeVillage: 1164,
        altitudeMin: 1164,
        altitudeMax: 2500,
        kmPistes: 120,
        openMeteoElevation: 2200,
        snowForecastSlug: "Les-Contamines",
        skiinfoSlug: "les-contamines-montjoie",
    },

    // ──────── TARENTAISE ────────
    {
        id: "val-thorens",
        name: "Val Thorens",
        slug: "val-thorens",
        massif: "Tarentaise",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.2981,
        lon: 6.5847,
        altitudeVillage: 2300,
        altitudeMin: 1300,
        altitudeMax: 3230,
        kmPistes: 600,
        openMeteoElevation: 2800,
        snowForecastSlug: "Val-Thorens",
        skiinfoSlug: "val-thorens",
    },
    {
        id: "courchevel",
        name: "Courchevel",
        slug: "courchevel",
        massif: "Tarentaise",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.4153,
        lon: 6.6347,
        altitudeVillage: 1850,
        altitudeMin: 1300,
        altitudeMax: 2738,
        kmPistes: 600,
        openMeteoElevation: 2400,
        snowForecastSlug: "Courchevel",
        skiinfoSlug: "courchevel",
    },
    {
        id: "meribel",
        name: "Méribel",
        slug: "meribel",
        massif: "Tarentaise",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.3968,
        lon: 6.5656,
        altitudeVillage: 1450,
        altitudeMin: 1100,
        altitudeMax: 2952,
        kmPistes: 600,
        openMeteoElevation: 2400,
        snowForecastSlug: "Meribel",
        skiinfoSlug: "meribel",
    },
    {
        id: "la-plagne",
        name: "La Plagne",
        slug: "la-plagne",
        massif: "Tarentaise",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.5064,
        lon: 6.6778,
        altitudeVillage: 2100,
        altitudeMin: 1250,
        altitudeMax: 3250,
        kmPistes: 225,
        openMeteoElevation: 2500,
        snowForecastSlug: "La-Plagne",
        skiinfoSlug: "la-plagne",
    },
    {
        id: "les-arcs",
        name: "Les Arcs",
        slug: "les-arcs",
        massif: "Tarentaise",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.5733,
        lon: 6.8281,
        altitudeVillage: 1800,
        altitudeMin: 1200,
        altitudeMax: 3226,
        kmPistes: 200,
        openMeteoElevation: 2500,
        snowForecastSlug: "Les-Arcs",
        skiinfoSlug: "les-arcs",
    },
    {
        id: "tignes",
        name: "Tignes",
        slug: "tignes",
        massif: "Tarentaise",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.4689,
        lon: 6.9056,
        altitudeVillage: 2100,
        altitudeMin: 1550,
        altitudeMax: 3456,
        kmPistes: 300,
        openMeteoElevation: 2800,
        snowForecastSlug: "Tignes",
        skiinfoSlug: "tignes",
    },
    {
        id: "val-disere",
        name: "Val d'Isère",
        slug: "val-disere",
        massif: "Tarentaise",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.4481,
        lon: 6.9808,
        altitudeVillage: 1850,
        altitudeMin: 1550,
        altitudeMax: 3456,
        kmPistes: 300,
        openMeteoElevation: 2800,
        snowForecastSlug: "Val-d-Isere",
        skiinfoSlug: "val-d-isere",
    },
    {
        id: "sainte-foy",
        name: "Sainte-Foy-Tarentaise",
        slug: "sainte-foy",
        massif: "Tarentaise",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.5842,
        lon: 6.8847,
        altitudeVillage: 1550,
        altitudeMin: 1550,
        altitudeMax: 2620,
        kmPistes: 42,
        openMeteoElevation: 2200,
        snowForecastSlug: "Sainte-Foy-Tarentaise",
        skiinfoSlug: "sainte-foy-tarentaise",
    },

    // ──────── VANOISE ────────
    {
        id: "la-rosiere",
        name: "La Rosière",
        slug: "la-rosiere",
        massif: "Vanoise",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.6286,
        lon: 6.8483,
        altitudeVillage: 1850,
        altitudeMin: 1176,
        altitudeMax: 2800,
        kmPistes: 160,
        openMeteoElevation: 2400,
        snowForecastSlug: "La-Rosiere",
        skiinfoSlug: "la-rosiere",
    },
    {
        id: "pralognan",
        name: "Pralognan-la-Vanoise",
        slug: "pralognan",
        massif: "Vanoise",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.3833,
        lon: 6.7167,
        altitudeVillage: 1410,
        altitudeMin: 1410,
        altitudeMax: 2355,
        kmPistes: 25,
        openMeteoElevation: 2000,
        snowForecastSlug: "Pralognan-la-Vanoise",
        skiinfoSlug: "pralognan-la-vanoise",
    },

    // ──────── BEAUFORTAIN ────────
    {
        id: "hauteluce",
        name: "Hauteluce – Les Saisies",
        slug: "hauteluce",
        massif: "Beaufortain",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.7556,
        lon: 6.5322,
        altitudeVillage: 1650,
        altitudeMin: 1000,
        altitudeMax: 2069,
        kmPistes: 192,
        openMeteoElevation: 1800,
        snowForecastSlug: "Les-Saisies",
        skiinfoSlug: "les-saisies",
    },

    // ──────── ARAVIS ────────
    {
        id: "la-clusaz",
        name: "La Clusaz",
        slug: "la-clusaz",
        massif: "Aravis",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.9044,
        lon: 6.4233,
        altitudeVillage: 1040,
        altitudeMin: 1040,
        altitudeMax: 2616,
        kmPistes: 125,
        openMeteoElevation: 2200,
        snowForecastSlug: "La-Clusaz",
        skiinfoSlug: "la-clusaz",
    },
    {
        id: "le-grand-bornand",
        name: "Le Grand-Bornand",
        slug: "le-grand-bornand",
        massif: "Aravis",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.9422,
        lon: 6.4297,
        altitudeVillage: 950,
        altitudeMin: 950,
        altitudeMax: 2100,
        kmPistes: 90,
        openMeteoElevation: 1800,
        snowForecastSlug: "Le-Grand-Bornand",
        skiinfoSlug: "le-grand-bornand",
    },

    // ──────── CHABLAIS ────────
    {
        id: "avoriaz",
        name: "Avoriaz",
        slug: "avoriaz",
        massif: "Chablais",
        region: "Auvergne-Rhône-Alpes",
        lat: 46.1908,
        lon: 6.7731,
        altitudeVillage: 1800,
        altitudeMin: 1000,
        altitudeMax: 2466,
        kmPistes: 650,
        openMeteoElevation: 2200,
        snowForecastSlug: "Avoriaz",
        skiinfoSlug: "avoriaz",
    },
    {
        id: "morzine",
        name: "Morzine",
        slug: "morzine",
        massif: "Chablais",
        region: "Auvergne-Rhône-Alpes",
        lat: 46.1792,
        lon: 6.7089,
        altitudeVillage: 1000,
        altitudeMin: 1000,
        altitudeMax: 2466,
        kmPistes: 650,
        openMeteoElevation: 2000,
        snowForecastSlug: "Morzine",
        skiinfoSlug: "morzine",
    },
    {
        id: "chatel",
        name: "Châtel",
        slug: "chatel",
        massif: "Chablais",
        region: "Auvergne-Rhône-Alpes",
        lat: 46.2667,
        lon: 6.8411,
        altitudeVillage: 1200,
        altitudeMin: 1100,
        altitudeMax: 2200,
        kmPistes: 650,
        openMeteoElevation: 1800,
        snowForecastSlug: "Chatel",
        skiinfoSlug: "chatel",
    },

    // ──────── GIFFRE ────────
    {
        id: "flaine",
        name: "Flaine",
        slug: "flaine",
        massif: "Giffre",
        region: "Auvergne-Rhône-Alpes",
        lat: 46.0056,
        lon: 6.6889,
        altitudeVillage: 1600,
        altitudeMin: 700,
        altitudeMax: 2500,
        kmPistes: 265,
        openMeteoElevation: 2200,
        snowForecastSlug: "Flaine",
        skiinfoSlug: "flaine",
    },
    {
        id: "samoens",
        name: "Samoëns",
        slug: "samoens",
        massif: "Giffre",
        region: "Auvergne-Rhône-Alpes",
        lat: 46.0833,
        lon: 6.7333,
        altitudeVillage: 720,
        altitudeMin: 720,
        altitudeMax: 2500,
        kmPistes: 265,
        openMeteoElevation: 2000,
        snowForecastSlug: "Samoens",
        skiinfoSlug: "samoens",
    },

    // ──────── BELLEDONNE ────────
    {
        id: "chamrousse",
        name: "Chamrousse",
        slug: "chamrousse",
        massif: "Belledonne",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.1178,
        lon: 5.8781,
        altitudeVillage: 1700,
        altitudeMin: 1400,
        altitudeMax: 2253,
        kmPistes: 90,
        openMeteoElevation: 2000,
        snowForecastSlug: "Chamrousse",
        skiinfoSlug: "chamrousse",
    },

    // ──────── GRANDES ROUSSES ────────
    {
        id: "alpe-dhuez",
        name: "Alpe d'Huez",
        slug: "alpe-dhuez",
        massif: "Grandes Rousses",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.0911,
        lon: 6.0683,
        altitudeVillage: 1860,
        altitudeMin: 1120,
        altitudeMax: 3330,
        kmPistes: 250,
        openMeteoElevation: 2600,
        snowForecastSlug: "Alpe-d-Huez",
        skiinfoSlug: "alpe-d-huez-grand-domaine-ski",
    },

    // ──────── OISANS ────────
    {
        id: "les-deux-alpes",
        name: "Les 2 Alpes",
        slug: "les-deux-alpes",
        massif: "Oisans",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.0167,
        lon: 6.1222,
        altitudeVillage: 1650,
        altitudeMin: 1300,
        altitudeMax: 3600,
        kmPistes: 200,
        openMeteoElevation: 2800,
        snowForecastSlug: "Les-Deux-Alpes",
        skiinfoSlug: "les-2-alpes",
    },

    // ──────── SERRE CHEVALIER ────────
    {
        id: "serre-chevalier",
        name: "Serre Chevalier",
        slug: "serre-chevalier",
        massif: "Serre Chevalier",
        region: "Provence-Alpes-Côte d'Azur",
        lat: 44.9497,
        lon: 6.5878,
        altitudeVillage: 1200,
        altitudeMin: 1200,
        altitudeMax: 2800,
        kmPistes: 250,
        openMeteoElevation: 2400,
        snowForecastSlug: "Serre-Chevalier",
        skiinfoSlug: "serre-chevalier",
    },
    {
        id: "montgenèvre",
        name: "Montgenèvre",
        slug: "montgenevre",
        massif: "Serre Chevalier",
        region: "Provence-Alpes-Côte d'Azur",
        lat: 44.9325,
        lon: 6.7231,
        altitudeVillage: 1860,
        altitudeMin: 1400,
        altitudeMax: 2700,
        kmPistes: 100,
        openMeteoElevation: 2300,
        snowForecastSlug: "Montgenevre",
        skiinfoSlug: "montgenevre",
    },

    // ──────── ÉCRINS ────────
    {
        id: "pelvoux-vallouise",
        name: "Pelvoux-Vallouise",
        slug: "pelvoux-vallouise",
        massif: "Écrins",
        region: "Provence-Alpes-Côte d'Azur",
        lat: 44.8614,
        lon: 6.4908,
        altitudeVillage: 1250,
        altitudeMin: 1250,
        altitudeMax: 2300,
        kmPistes: 30,
        openMeteoElevation: 2000,
        snowForecastSlug: "Pelvoux",
        skiinfoSlug: "pelvoux-vallouise",
    },

    // ──────── QUEYRAS ────────
    {
        id: "vars",
        name: "Vars",
        slug: "vars",
        massif: "Queyras",
        region: "Provence-Alpes-Côte d'Azur",
        lat: 44.5797,
        lon: 6.6903,
        altitudeVillage: 1850,
        altitudeMin: 1650,
        altitudeMax: 2750,
        kmPistes: 185,
        openMeteoElevation: 2400,
        snowForecastSlug: "Vars",
        skiinfoSlug: "vars",
    },
    {
        id: "risoul",
        name: "Risoul",
        slug: "risoul",
        massif: "Queyras",
        region: "Provence-Alpes-Côte d'Azur",
        lat: 44.6167,
        lon: 6.6333,
        altitudeVillage: 1850,
        altitudeMin: 1850,
        altitudeMax: 2750,
        kmPistes: 185,
        openMeteoElevation: 2400,
        snowForecastSlug: "Risoul",
        skiinfoSlug: "risoul",
    },

    // ──────── UBAYE ────────
    {
        id: "pra-loup",
        name: "Pra Loup",
        slug: "pra-loup",
        massif: "Ubaye",
        region: "Provence-Alpes-Côte d'Azur",
        lat: 44.3669,
        lon: 6.6028,
        altitudeVillage: 1600,
        altitudeMin: 1500,
        altitudeMax: 2600,
        kmPistes: 180,
        openMeteoElevation: 2200,
        snowForecastSlug: "Pra-Loup",
        skiinfoSlug: "pra-loup",
    },

    // ──────── MAURIENNE ────────
    {
        id: "valmeinier",
        name: "Valmeinier",
        slug: "valmeinier",
        massif: "Maurienne",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.1167,
        lon: 6.4833,
        altitudeVillage: 1500,
        altitudeMin: 1500,
        altitudeMax: 2600,
        kmPistes: 165,
        openMeteoElevation: 2200,
        snowForecastSlug: "Valmeinier",
        skiinfoSlug: "valmeinier",
    },
    {
        id: "valloire",
        name: "Valloire",
        slug: "valloire",
        massif: "Maurienne",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.1647,
        lon: 6.4281,
        altitudeVillage: 1430,
        altitudeMin: 1430,
        altitudeMax: 2600,
        kmPistes: 165,
        openMeteoElevation: 2200,
        snowForecastSlug: "Valloire",
        skiinfoSlug: "valloire",
    },

    // ──────── MERCANTOUR ────────
    {
        id: "isola-2000",
        name: "Isola 2000",
        slug: "isola-2000",
        massif: "Mercantour",
        region: "Provence-Alpes-Côte d'Azur",
        lat: 44.1864,
        lon: 7.1594,
        altitudeVillage: 2000,
        altitudeMin: 1800,
        altitudeMax: 2610,
        kmPistes: 120,
        openMeteoElevation: 2300,
        snowForecastSlug: "Isola-2000",
        skiinfoSlug: "isola-2000",
    },
    {
        id: "auron",
        name: "Auron",
        slug: "auron",
        massif: "Mercantour",
        region: "Provence-Alpes-Côte d'Azur",
        lat: 44.2081,
        lon: 6.9325,
        altitudeVillage: 1600,
        altitudeMin: 1600,
        altitudeMax: 2450,
        kmPistes: 135,
        openMeteoElevation: 2100,
        snowForecastSlug: "Auron",
        skiinfoSlug: "auron",
    },

    // ──────── VERCORS ────────
    {
        id: "villard-de-lans",
        name: "Villard-de-Lans",
        slug: "villard-de-lans",
        massif: "Vercors",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.0719,
        lon: 5.5478,
        altitudeVillage: 1050,
        altitudeMin: 1050,
        altitudeMax: 2170,
        kmPistes: 125,
        openMeteoElevation: 1800,
        snowForecastSlug: "Villard-de-Lans",
        skiinfoSlug: "villard-de-lans",
    },

    // ──────── CHARTREUSE ────────
    {
        id: "col-de-porte",
        name: "Col de Porte",
        slug: "col-de-porte",
        massif: "Chartreuse",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.3,
        lon: 5.7667,
        altitudeVillage: 1326,
        altitudeMin: 1200,
        altitudeMax: 1450,
        kmPistes: 15,
        openMeteoElevation: 1400,
        snowForecastSlug: null,
        skiinfoSlug: null,
    },

    // ──────── DÉVOLUY ────────
    {
        id: "superdevoluy",
        name: "SuperDévoluy",
        slug: "superdevoluy",
        massif: "Dévoluy",
        region: "Provence-Alpes-Côte d'Azur",
        lat: 44.6667,
        lon: 5.9333,
        altitudeVillage: 1500,
        altitudeMin: 1500,
        altitudeMax: 2500,
        kmPistes: 100,
        openMeteoElevation: 2200,
        snowForecastSlug: "SuperDevoluy",
        skiinfoSlug: "superdevoluy",
    },

    // ──────── PYRÉNÉES CENTRALES ────────
    {
        id: "saint-lary",
        name: "Saint-Lary-Soulan",
        slug: "saint-lary",
        massif: "Pyrénées Centrales",
        region: "Occitanie",
        lat: 42.8167,
        lon: 0.3167,
        altitudeVillage: 830,
        altitudeMin: 1680,
        altitudeMax: 2515,
        kmPistes: 100,
        openMeteoElevation: 2200,
        snowForecastSlug: "Saint-Lary-Soulan",
        skiinfoSlug: "saint-lary-soulan",
    },
    {
        id: "piau-engaly",
        name: "Piau-Engaly",
        slug: "piau-engaly",
        massif: "Pyrénées Centrales",
        region: "Occitanie",
        lat: 42.7833,
        lon: 0.15,
        altitudeVillage: 1850,
        altitudeMin: 1420,
        altitudeMax: 2528,
        kmPistes: 65,
        openMeteoElevation: 2200,
        snowForecastSlug: "Piau-Engaly",
        skiinfoSlug: "piau-engaly",
    },
    {
        id: "grand-tourmalet",
        name: "Grand Tourmalet (Barèges/La Mongie)",
        slug: "grand-tourmalet",
        massif: "Pyrénées Centrales",
        region: "Occitanie",
        lat: 42.9,
        lon: 0.15,
        altitudeVillage: 1250,
        altitudeMin: 1250,
        altitudeMax: 2500,
        kmPistes: 100,
        openMeteoElevation: 2200,
        snowForecastSlug: "Bareges",
        skiinfoSlug: "grand-tourmalet-bareges-la-mongie",
    },
    {
        id: "cauterets",
        name: "Cauterets",
        slug: "cauterets",
        massif: "Pyrénées Centrales",
        region: "Occitanie",
        lat: 42.8892,
        lon: -0.1117,
        altitudeVillage: 930,
        altitudeMin: 930,
        altitudeMax: 2450,
        kmPistes: 36,
        openMeteoElevation: 2000,
        snowForecastSlug: "Cauterets",
        skiinfoSlug: "cauterets",
    },
    {
        id: "luz-ardiden",
        name: "Luz Ardiden",
        slug: "luz-ardiden",
        massif: "Pyrénées Centrales",
        region: "Occitanie",
        lat: 42.8667,
        lon: -0.05,
        altitudeVillage: 1680,
        altitudeMin: 1680,
        altitudeMax: 2500,
        kmPistes: 60,
        openMeteoElevation: 2200,
        snowForecastSlug: "Luz-Ardiden",
        skiinfoSlug: "luz-ardiden",
    },
    {
        id: "luchon-superbagneres",
        name: "Luchon-Superbagnères",
        slug: "luchon-superbagneres",
        massif: "Pyrénées Centrales",
        region: "Occitanie",
        lat: 42.7667,
        lon: 0.6333,
        altitudeVillage: 1440,
        altitudeMin: 1440,
        altitudeMax: 2260,
        kmPistes: 28,
        openMeteoElevation: 2000,
        snowForecastSlug: "Luchon-Superbagneres",
        skiinfoSlug: "luchon-superbagneres",
    },

    // ──────── PYRÉNÉES ORIENTALES ────────
    {
        id: "font-romeu",
        name: "Font-Romeu / Pyrénées 2000",
        slug: "font-romeu",
        massif: "Pyrénées Orientales",
        region: "Occitanie",
        lat: 42.5036,
        lon: 2.0361,
        altitudeVillage: 1800,
        altitudeMin: 1700,
        altitudeMax: 2213,
        kmPistes: 43,
        openMeteoElevation: 2000,
        snowForecastSlug: "Font-Romeu",
        skiinfoSlug: "font-romeu-pyrenees-2000",
    },
    {
        id: "les-angles",
        name: "Les Angles",
        slug: "les-angles",
        massif: "Pyrénées Orientales",
        region: "Occitanie",
        lat: 42.5714,
        lon: 2.0722,
        altitudeVillage: 1650,
        altitudeMin: 1600,
        altitudeMax: 2400,
        kmPistes: 55,
        openMeteoElevation: 2100,
        snowForecastSlug: "Les-Angles",
        skiinfoSlug: "les-angles",
    },
    {
        id: "ax-3-domaines",
        name: "Ax 3 Domaines",
        slug: "ax-3-domaines",
        massif: "Pyrénées Orientales",
        region: "Occitanie",
        lat: 42.7208,
        lon: 1.8381,
        altitudeVillage: 1400,
        altitudeMin: 1400,
        altitudeMax: 2400,
        kmPistes: 80,
        openMeteoElevation: 2000,
        snowForecastSlug: "Ax-3-Domaines",
        skiinfoSlug: "ax-3-domaines",
    },

    // ──────── PYRÉNÉES ATLANTIQUES ────────
    {
        id: "gourette",
        name: "Gourette",
        slug: "gourette",
        massif: "Pyrénées Atlantiques",
        region: "Nouvelle-Aquitaine",
        lat: 42.9606,
        lon: -0.3358,
        altitudeVillage: 1400,
        altitudeMin: 1400,
        altitudeMax: 2450,
        kmPistes: 40,
        openMeteoElevation: 2000,
        snowForecastSlug: "Gourette",
        skiinfoSlug: "gourette",
    },
    {
        id: "la-pierre-saint-martin",
        name: "La Pierre Saint-Martin",
        slug: "la-pierre-saint-martin",
        massif: "Pyrénées Atlantiques",
        region: "Nouvelle-Aquitaine",
        lat: 42.9736,
        lon: -0.7514,
        altitudeVillage: 1527,
        altitudeMin: 1527,
        altitudeMax: 2153,
        kmPistes: 25,
        openMeteoElevation: 1800,
        snowForecastSlug: "La-Pierre-Saint-Martin",
        skiinfoSlug: "la-pierre-saint-martin",
    },

    // ──────── JURA ────────
    {
        id: "metabief",
        name: "Métabief",
        slug: "metabief",
        massif: "Jura",
        region: "Bourgogne-Franche-Comté",
        lat: 46.7703,
        lon: 6.3536,
        altitudeVillage: 1000,
        altitudeMin: 900,
        altitudeMax: 1420,
        kmPistes: 40,
        openMeteoElevation: 1300,
        snowForecastSlug: "Metabief",
        skiinfoSlug: "metabief",
    },

    // ──────── VOSGES ────────
    {
        id: "la-bresse",
        name: "La Bresse – Hohneck",
        slug: "la-bresse",
        massif: "Vosges",
        region: "Grand Est",
        lat: 48.0,
        lon: 6.8833,
        altitudeVillage: 630,
        altitudeMin: 900,
        altitudeMax: 1350,
        kmPistes: 50,
        openMeteoElevation: 1200,
        snowForecastSlug: "La-Bresse-Hohneck",
        skiinfoSlug: "la-bresse-hohneck",
    },

    // ──────── MASSIF CENTRAL ────────
    {
        id: "super-besse",
        name: "Super Besse",
        slug: "super-besse",
        massif: "Massif Central",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.5167,
        lon: 2.85,
        altitudeVillage: 1350,
        altitudeMin: 1300,
        altitudeMax: 1850,
        kmPistes: 43,
        openMeteoElevation: 1600,
        snowForecastSlug: "Super-Besse",
        skiinfoSlug: "super-besse",
    },
    {
        id: "le-mont-dore",
        name: "Le Mont-Dore",
        slug: "le-mont-dore",
        massif: "Massif Central",
        region: "Auvergne-Rhône-Alpes",
        lat: 45.5733,
        lon: 2.81,
        altitudeVillage: 1050,
        altitudeMin: 1200,
        altitudeMax: 1846,
        kmPistes: 33,
        openMeteoElevation: 1600,
        snowForecastSlug: "Le-Mont-Dore",
        skiinfoSlug: "le-mont-dore",
    },
];

// ──────── HELPERS ────────
// export function getStationBySlug(slug: string): Station | undefined {
//   return STATIONS.find((s) => s.slug === slug);
// }
//
// export function getStationsByMassif(massif: string): Station[] {
//   return STATIONS.filter((s) => s.massif === massif);
// }
//
// export function getStationsByRegion(region: string): Station[] {
//   return STATIONS.filter((s) => s.region === region);
// }
//
// export function getAllMassifs(): string[] {
//   return [...new Set(STATIONS.map((s) => s.massif))].sort();
// }
//
// export function getAllRegions(): string[] {
//   return [...new Set(STATIONS.map((s) => s.region))].sort();
// }
