import type { Station } from "./types";

export const STATIONS: Station[] = [
  // ──────── MONT-BLANC ────────
  {
    id: "chamonix",
    name: "Chamonix Mont-Blanc",
    slug: "chamonix",
    massif: "Mont-Blanc",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.9237,
    lon: 6.8694,
    altitudeVillage: 1035,
    altitudeMin: 1035,
    altitudeMax: 3842,
    kmPistes: 155,
    openMeteoElevation: 3000,
  },
  {
    id: "megeve",
    name: "Megève",
    slug: "megeve",
    massif: "Mont-Blanc",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.8567,
    lon: 6.6175,
    altitudeVillage: 1113,
    altitudeMin: 850,
    altitudeMax: 2350,
    kmPistes: 400,
    openMeteoElevation: 2000,
  },
  {
    id: "les-contamines",
    name: "Les Contamines-Montjoie",
    slug: "les-contamines",
    massif: "Mont-Blanc",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.8211,
    lon: 6.7267,
    altitudeVillage: 1164,
    altitudeMin: 1164,
    altitudeMax: 2500,
    kmPistes: 120,
    openMeteoElevation: 2200,
  },

  // ──────── TARENTAISE ────────
  {
    id: "val-thorens",
    name: "Val Thorens",
    slug: "val-thorens",
    massif: "Tarentaise",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.2981,
    lon: 6.5847,
    altitudeVillage: 2300,
    altitudeMin: 1300,
    altitudeMax: 3230,
    kmPistes: 600,
    openMeteoElevation: 2800,
  },
  {
    id: "courchevel",
    name: "Courchevel",
    slug: "courchevel",
    massif: "Tarentaise",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.4153,
    lon: 6.6347,
    altitudeVillage: 1850,
    altitudeMin: 1300,
    altitudeMax: 2738,
    kmPistes: 600,
    openMeteoElevation: 2400,
  },
  {
    id: "meribel",
    name: "Méribel",
    slug: "meribel",
    massif: "Tarentaise",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.3967,
    lon: 6.5656,
    altitudeVillage: 1450,
    altitudeMin: 1100,
    altitudeMax: 2952,
    kmPistes: 600,
    openMeteoElevation: 2400,
  },
  {
    id: "la-plagne",
    name: "La Plagne",
    slug: "la-plagne",
    massif: "Tarentaise",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.5069,
    lon: 6.6772,
    altitudeVillage: 2100,
    altitudeMin: 1250,
    altitudeMax: 3250,
    kmPistes: 425,
    openMeteoElevation: 2600,
  },
  {
    id: "les-arcs",
    name: "Les Arcs",
    slug: "les-arcs",
    massif: "Tarentaise",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.5733,
    lon: 6.8283,
    altitudeVillage: 1600,
    altitudeMin: 1200,
    altitudeMax: 3226,
    kmPistes: 425,
    openMeteoElevation: 2600,
  },
  {
    id: "tignes",
    name: "Tignes",
    slug: "tignes",
    massif: "Tarentaise",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.4686,
    lon: 6.9064,
    altitudeVillage: 2100,
    altitudeMin: 1550,
    altitudeMax: 3456,
    kmPistes: 300,
    openMeteoElevation: 2800,
  },
  {
    id: "val-disere",
    name: "Val d'Isère",
    slug: "val-disere",
    massif: "Tarentaise",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.4481,
    lon: 6.9808,
    altitudeVillage: 1850,
    altitudeMin: 1550,
    altitudeMax: 3456,
    kmPistes: 300,
    openMeteoElevation: 2800,
  },
  {
    id: "sainte-foy",
    name: "Sainte-Foy-Tarentaise",
    slug: "sainte-foy",
    massif: "Tarentaise",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.4833,
    lon: 6.8833,
    altitudeVillage: 1550,
    altitudeMin: 1550,
    altitudeMax: 2620,
    kmPistes: 42,
    openMeteoElevation: 2200,
  },

  // ──────── VANOISE ────────
  {
    id: "pralognan",
    name: "Pralognan-la-Vanoise",
    slug: "pralognan",
    massif: "Vanoise",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.3831,
    lon: 6.7189,
    altitudeVillage: 1410,
    altitudeMin: 1410,
    altitudeMax: 2355,
    kmPistes: 25,
    openMeteoElevation: 2000,
  },

  // ──────── MAURIENNE ────────
  {
    id: "valmeinier",
    name: "Valmeinier",
    slug: "valmeinier",
    massif: "Maurienne",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.1833,
    lon: 6.4833,
    altitudeVillage: 1500,
    altitudeMin: 1500,
    altitudeMax: 2600,
    kmPistes: 165,
    openMeteoElevation: 2200,
  },
  {
    id: "valloire",
    name: "Valloire",
    slug: "valloire",
    massif: "Maurienne",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.1642,
    lon: 6.4289,
    altitudeVillage: 1430,
    altitudeMin: 1430,
    altitudeMax: 2600,
    kmPistes: 165,
    openMeteoElevation: 2200,
  },

  // ──────── BEAUFORTAIN ────────
  {
    id: "les-saisies",
    name: "Les Saisies",
    slug: "les-saisies",
    massif: "Beaufortain",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.7606,
    lon: 6.5331,
    altitudeVillage: 1650,
    altitudeMin: 1650,
    altitudeMax: 2069,
    kmPistes: 77,
    openMeteoElevation: 1900,
  },

  // ──────── ARAVIS ────────
  {
    id: "la-clusaz",
    name: "La Clusaz",
    slug: "la-clusaz",
    massif: "Aravis",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.9044,
    lon: 6.4236,
    altitudeVillage: 1100,
    altitudeMin: 1100,
    altitudeMax: 2600,
    kmPistes: 125,
    openMeteoElevation: 2100,
  },
  {
    id: "le-grand-bornand",
    name: "Le Grand-Bornand",
    slug: "le-grand-bornand",
    massif: "Aravis",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.9422,
    lon: 6.4286,
    altitudeVillage: 1000,
    altitudeMin: 1000,
    altitudeMax: 2100,
    kmPistes: 84,
    openMeteoElevation: 1800,
  },
  {
    id: "manigod",
    name: "Manigod",
    slug: "manigod",
    massif: "Aravis",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.8567,
    lon: 6.3667,
    altitudeVillage: 1460,
    altitudeMin: 1460,
    altitudeMax: 2100,
    kmPistes: 29,
    openMeteoElevation: 1800,
  },

  // ──────── CHABLAIS ────────
  {
    id: "avoriaz",
    name: "Avoriaz",
    slug: "avoriaz",
    massif: "Chablais",
    region: "Auvergne-Rhône-Alpes",
    lat: 46.1911,
    lon: 6.7744,
    altitudeVillage: 1800,
    altitudeMin: 1100,
    altitudeMax: 2466,
    kmPistes: 650,
    openMeteoElevation: 2200,
  },
  {
    id: "morzine",
    name: "Morzine",
    slug: "morzine",
    massif: "Chablais",
    region: "Auvergne-Rhône-Alpes",
    lat: 46.1797,
    lon: 6.7094,
    altitudeVillage: 1000,
    altitudeMin: 1000,
    altitudeMax: 2466,
    kmPistes: 650,
    openMeteoElevation: 2000,
  },
  {
    id: "chatel",
    name: "Châtel",
    slug: "chatel",
    massif: "Chablais",
    region: "Auvergne-Rhône-Alpes",
    lat: 46.2667,
    lon: 6.8417,
    altitudeVillage: 1200,
    altitudeMin: 1100,
    altitudeMax: 2200,
    kmPistes: 650,
    openMeteoElevation: 1800,
  },

  // ──────── GIFFRE ────────
  {
    id: "flaine",
    name: "Flaine",
    slug: "flaine",
    massif: "Giffre",
    region: "Auvergne-Rhône-Alpes",
    lat: 46.0058,
    lon: 6.6889,
    altitudeVillage: 1600,
    altitudeMin: 700,
    altitudeMax: 2500,
    kmPistes: 265,
    openMeteoElevation: 2100,
  },
  {
    id: "samoens",
    name: "Samoëns",
    slug: "samoens",
    massif: "Giffre",
    region: "Auvergne-Rhône-Alpes",
    lat: 46.0833,
    lon: 6.7333,
    altitudeVillage: 720,
    altitudeMin: 700,
    altitudeMax: 2500,
    kmPistes: 265,
    openMeteoElevation: 2000,
  },

  // ──────── BELLEDONNE ────────
  {
    id: "chamrousse",
    name: "Chamrousse",
    slug: "chamrousse",
    massif: "Belledonne",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.1178,
    lon: 5.8789,
    altitudeVillage: 1750,
    altitudeMin: 1650,
    altitudeMax: 2250,
    kmPistes: 90,
    openMeteoElevation: 2100,
  },

  // ──────── GRANDES ROUSSES / OISANS ────────
  {
    id: "alpe-dhuez",
    name: "Alpe d'Huez",
    slug: "alpe-dhuez",
    massif: "Grandes Rousses",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.0911,
    lon: 6.0683,
    altitudeVillage: 1860,
    altitudeMin: 1120,
    altitudeMax: 3330,
    kmPistes: 250,
    openMeteoElevation: 2600,
  },
  {
    id: "les-deux-alpes",
    name: "Les 2 Alpes",
    slug: "les-deux-alpes",
    massif: "Oisans",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.0167,
    lon: 6.1222,
    altitudeVillage: 1650,
    altitudeMin: 1300,
    altitudeMax: 3600,
    kmPistes: 225,
    openMeteoElevation: 2800,
  },

  // ──────── ÉCRINS / SERRE CHEVALIER ────────
  {
    id: "serre-chevalier",
    name: "Serre Chevalier",
    slug: "serre-chevalier",
    massif: "Serre Chevalier",
    region: "Provence-Alpes-Côte d'Azur",
    lat: 44.9419,
    lon: 6.5061,
    altitudeVillage: 1200,
    altitudeMin: 1200,
    altitudeMax: 2800,
    kmPistes: 250,
    openMeteoElevation: 2400,
  },
  {
    id: "la-grave",
    name: "La Grave",
    slug: "la-grave",
    massif: "Écrins",
    region: "Provence-Alpes-Côte d'Azur",
    lat: 45.0458,
    lon: 6.3053,
    altitudeVillage: 1450,
    altitudeMin: 1450,
    altitudeMax: 3568,
    kmPistes: 15,
    openMeteoElevation: 3000,
  },
  {
    id: "puy-saint-vincent",
    name: "Puy-Saint-Vincent",
    slug: "puy-saint-vincent",
    massif: "Écrins",
    region: "Provence-Alpes-Côte d'Azur",
    lat: 44.8308,
    lon: 6.4881,
    altitudeVillage: 1400,
    altitudeMin: 1400,
    altitudeMax: 2700,
    kmPistes: 75,
    openMeteoElevation: 2200,
  },

  // ──────── QUEYRAS ────────
  {
    id: "vars",
    name: "Vars",
    slug: "vars",
    massif: "Queyras",
    region: "Provence-Alpes-Côte d'Azur",
    lat: 44.5592,
    lon: 6.6686,
    altitudeVillage: 1850,
    altitudeMin: 1650,
    altitudeMax: 2750,
    kmPistes: 185,
    openMeteoElevation: 2400,
  },
  {
    id: "risoul",
    name: "Risoul",
    slug: "risoul",
    massif: "Queyras",
    region: "Provence-Alpes-Côte d'Azur",
    lat: 44.6250,
    lon: 6.6361,
    altitudeVillage: 1850,
    altitudeMin: 1650,
    altitudeMax: 2750,
    kmPistes: 185,
    openMeteoElevation: 2400,
  },

  // ──────── UBAYE ────────
  {
    id: "pra-loup",
    name: "Pra Loup",
    slug: "pra-loup",
    massif: "Ubaye",
    region: "Provence-Alpes-Côte d'Azur",
    lat: 44.3631,
    lon: 6.6008,
    altitudeVillage: 1600,
    altitudeMin: 1500,
    altitudeMax: 2600,
    kmPistes: 180,
    openMeteoElevation: 2200,
  },

  // ──────── MERCANTOUR ────────
  {
    id: "isola-2000",
    name: "Isola 2000",
    slug: "isola-2000",
    massif: "Mercantour",
    region: "Provence-Alpes-Côte d'Azur",
    lat: 44.1867,
    lon: 7.1614,
    altitudeVillage: 2000,
    altitudeMin: 1800,
    altitudeMax: 2610,
    kmPistes: 120,
    openMeteoElevation: 2400,
  },
  {
    id: "auron",
    name: "Auron",
    slug: "auron",
    massif: "Mercantour",
    region: "Provence-Alpes-Côte d'Azur",
    lat: 44.2344,
    lon: 6.9317,
    altitudeVillage: 1600,
    altitudeMin: 1600,
    altitudeMax: 2450,
    kmPistes: 135,
    openMeteoElevation: 2100,
  },

  // ──────── VERCORS ────────
  {
    id: "villard-de-lans",
    name: "Villard-de-Lans / Corrençon",
    slug: "villard-de-lans",
    massif: "Vercors",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.0714,
    lon: 5.5481,
    altitudeVillage: 1050,
    altitudeMin: 1150,
    altitudeMax: 2170,
    kmPistes: 125,
    openMeteoElevation: 1800,
  },

  // ──────── CHARTREUSE ────────
  {
    id: "col-de-porte",
    name: "Col de Porte",
    slug: "col-de-porte",
    massif: "Chartreuse",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.3000,
    lon: 5.7667,
    altitudeVillage: 1326,
    altitudeMin: 1326,
    altitudeMax: 1450,
    kmPistes: 8,
    openMeteoElevation: 1400,
  },

  // ──────── DÉVOLUY ────────
  {
    id: "superdevoluy",
    name: "SuperDévoluy",
    slug: "superdevoluy",
    massif: "Dévoluy",
    region: "Provence-Alpes-Côte d'Azur",
    lat: 44.6778,
    lon: 5.9269,
    altitudeVillage: 1500,
    altitudeMin: 1500,
    altitudeMax: 2500,
    kmPistes: 100,
    openMeteoElevation: 2100,
  },

  // ──────── PYRÉNÉES CENTRALES ────────
  {
    id: "saint-lary",
    name: "Saint-Lary-Soulan",
    slug: "saint-lary",
    massif: "Pyrénées Centrales",
    region: "Occitanie",
    lat: 42.8164,
    lon: 0.3214,
    altitudeVillage: 830,
    altitudeMin: 1700,
    altitudeMax: 2515,
    kmPistes: 100,
    openMeteoElevation: 2200,
  },
  {
    id: "grand-tourmalet",
    name: "Grand Tourmalet (Barèges/La Mongie)",
    slug: "grand-tourmalet",
    massif: "Pyrénées Centrales",
    region: "Occitanie",
    lat: 42.9000,
    lon: 0.1500,
    altitudeVillage: 1250,
    altitudeMin: 1250,
    altitudeMax: 2500,
    kmPistes: 100,
    openMeteoElevation: 2200,
  },
  {
    id: "cauterets",
    name: "Cauterets",
    slug: "cauterets",
    massif: "Pyrénées Centrales",
    region: "Occitanie",
    lat: 42.8892,
    lon: -0.1119,
    altitudeVillage: 932,
    altitudeMin: 1850,
    altitudeMax: 2415,
    kmPistes: 36,
    openMeteoElevation: 2200,
  },
  {
    id: "peyragudes",
    name: "Peyragudes",
    slug: "peyragudes",
    massif: "Pyrénées Centrales",
    region: "Occitanie",
    lat: 42.7933,
    lon: 0.4508,
    altitudeVillage: 1600,
    altitudeMin: 1450,
    altitudeMax: 2400,
    kmPistes: 60,
    openMeteoElevation: 2100,
  },
  {
    id: "luchon-superbagneres",
    name: "Luchon-Superbagnères",
    slug: "luchon-superbagneres",
    massif: "Pyrénées Centrales",
    region: "Occitanie",
    lat: 42.7500,
    lon: 0.5833,
    altitudeVillage: 1440,
    altitudeMin: 1440,
    altitudeMax: 2260,
    kmPistes: 28,
    openMeteoElevation: 2000,
  },

  // ──────── PYRÉNÉES ORIENTALES ────────
  {
    id: "font-romeu",
    name: "Font-Romeu / Pyrénées 2000",
    slug: "font-romeu",
    massif: "Pyrénées Orientales",
    region: "Occitanie",
    lat: 42.5017,
    lon: 2.0372,
    altitudeVillage: 1800,
    altitudeMin: 1700,
    altitudeMax: 2213,
    kmPistes: 58,
    openMeteoElevation: 2000,
  },
  {
    id: "les-angles",
    name: "Les Angles",
    slug: "les-angles",
    massif: "Pyrénées Orientales",
    region: "Occitanie",
    lat: 42.5714,
    lon: 2.0722,
    altitudeVillage: 1650,
    altitudeMin: 1650,
    altitudeMax: 2400,
    kmPistes: 55,
    openMeteoElevation: 2100,
  },

  // ──────── PYRÉNÉES ATLANTIQUES ────────
  {
    id: "gourette",
    name: "Gourette",
    slug: "gourette",
    massif: "Pyrénées Atlantiques",
    region: "Nouvelle-Aquitaine",
    lat: 42.9608,
    lon: -0.3372,
    altitudeVillage: 1400,
    altitudeMin: 1400,
    altitudeMax: 2450,
    kmPistes: 40,
    openMeteoElevation: 2000,
  },
  {
    id: "la-pierre-saint-martin",
    name: "La Pierre Saint-Martin",
    slug: "la-pierre-saint-martin",
    massif: "Pyrénées Atlantiques",
    region: "Nouvelle-Aquitaine",
    lat: 42.9728,
    lon: -0.7533,
    altitudeVillage: 1527,
    altitudeMin: 1527,
    altitudeMax: 2153,
    kmPistes: 26,
    openMeteoElevation: 1900,
  },

  // ──────── JURA ────────
  {
    id: "metabief",
    name: "Métabief",
    slug: "metabief",
    massif: "Jura",
    region: "Bourgogne-Franche-Comté",
    lat: 46.7714,
    lon: 6.3533,
    altitudeVillage: 1000,
    altitudeMin: 900,
    altitudeMax: 1420,
    kmPistes: 40,
    openMeteoElevation: 1300,
  },

  // ──────── VOSGES ────────
  {
    id: "la-bresse",
    name: "La Bresse Hohneck",
    slug: "la-bresse",
    massif: "Vosges",
    region: "Grand Est",
    lat: 48.0000,
    lon: 6.8667,
    altitudeVillage: 650,
    altitudeMin: 900,
    altitudeMax: 1350,
    kmPistes: 50,
    openMeteoElevation: 1200,
  },

  // ──────── MASSIF CENTRAL ────────
  {
    id: "super-besse",
    name: "Super Besse",
    slug: "super-besse",
    massif: "Massif Central",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.5086,
    lon: 2.8519,
    altitudeVillage: 1350,
    altitudeMin: 1350,
    altitudeMax: 1850,
    kmPistes: 43,
    openMeteoElevation: 1700,
  },
  {
    id: "le-mont-dore",
    name: "Le Mont-Dore",
    slug: "le-mont-dore",
    massif: "Massif Central",
    region: "Auvergne-Rhône-Alpes",
    lat: 45.5736,
    lon: 2.8081,
    altitudeVillage: 1050,
    altitudeMin: 1200,
    altitudeMax: 1846,
    kmPistes: 33,
    openMeteoElevation: 1600,
  },
];

// ──────── HELPERS ────────

export function getStationBySlug(slug: string): Station | undefined {
  return STATIONS.find((s) => s.slug === slug);
}

export function getStationsByMassif(massif: string): Station[] {
  return STATIONS.filter((s) => s.massif === massif);
}

export function getStationsByRegion(region: string): Station[] {
  return STATIONS.filter((s) => s.region === region);
}

export function getAllMassifs(): string[] {
  return [...new Set(STATIONS.map((s) => s.massif))].sort();
}

export function getAllRegions(): string[] {
  return [...new Set(STATIONS.map((s) => s.region))].sort();
}
